### ISSUE TITLE
FastCorrect2: add noise may delete all tokens

### ISSUE THREAD

**Issue by Arrivederci** [microsoft/NeuralSpeech#10]
for example, 
in the beam=4 setting, 

for a unpaired text 
    `"eight twitter"`

add_noise.py may generate a nbest sample like 
    `"twitter # 皮 twitter # eight twitter # "`

after tokenization and alignment step,  we get
    `"<void> ▁tw it ter <void> 1 ||| 皮 ▁tw it ter <void> 1 ||| ▁eight ▁tw it ter # 1 |||| 0 -2 1 1 0 ||| -1 1 1 1 0 ||| 1 1 1 1 0"`,
    only 3 candidates left, which lead to **assertion error** when binarizing dataset.

I think the reason is the code below in align_cal_werdur_fast.py. It strips the rightmost space of the nbest sample line, so the empty candidate cannot be split by " # "
```
print("Loading: ", hypo_file)
with open(hypo_file, 'r', encoding='utf-8') as infile:
    for line in infile.readlines():
        all_hypo_line.append([i.strip().split() for i in line.strip().split(' # ')])
```

If the empty candidate is in the middle of nbest line, the data preprocessing steps works fine, but it will also cause error during training

**Comment by YichongLeng** [comment]
Thanks for pointing this out. I have fixed the empty-checking bug in add_noise.py about skipping the noised sentence whose tokens are all deleted.

**Comment by Arrivederci** [comment]
@YichongLeng 
I got an exception like this during training, seems to be a nbset dim problem too. I'm not sure if it's caused by the the empty candidate

```
Traceback (most recent call last):
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 283, in call_main
    torch.multiprocessing.spawn(
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 7 terminated with the following error:
Traceback (most recent call last):
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 270, in distributed_main
    main(args, **kwargs)
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/fairseq_cli/train.py", line 125, in main
    valid_losses, should_stop = train(args, trainer, task, epoch_itr)
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/fairseq_cli/train.py", line 204, in train
    for i, samples in enumerate(progress):
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/fairseq/logging/progress_bar.py", line 243, in __iter__
    for i, obj in enumerate(self.iterable, start=self.n):
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/fairseq/data/iterators.py", line 59, in __iter__
    for x in self.iterable:
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/fairseq/data/iterators.py", line 469, in _chunk_iterator
    for x in itr:
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/fairseq/data/iterators.py", line 59, in __iter__
    for x in self.iterable:
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/fairseq/data/iterators.py", line 591, in __next__
    raise item
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/fairseq/data/iterators.py", line 522, in run
    for item in self._source:
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ssd/muyt/anaconda3/envs/fairseq-cu101/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ssd6/exec/muyt/FastCorrect2/FC_utils/language_pair_dataset.py", line 830, in __getitem__
    for_wer_gather = torch.LongTensor(for_wer_gather_list).transpose(0, 1)
ValueError: expected sequence of length 4 at dim 1 (got 2)

```

**Comment by Arrivederci** [comment]
I removed samples containing empty candidates. The code works fine, thanks

**Comment by ZKG-DreamCatcher** [comment]
你好，希望能为我解答以下疑问：

在FastCorrect2 中的第一步，我的结果和你的不一样是为什么呢， beam=4 
例如：未配对的数据是：
```
  数学,是研究數量,结构以及空间等概念及其变化的一門学科
  莲花新城南苑
```
执行 add_noise.py 后的结果是：
```
数学,是研究數量,结构以及空间等概念及其变化的一門学科    数,是研究數量,结构以及空间等概念及其变化的益門学科      数学,是研究數量,结构翼及空间等概念及其变化的一門学科    数学,是研九數量,结构及空间等概念及其变化>的一門学科     数歇,是研揪數量,结构以及空间等概念及其变化的异門学科
莲花新城南苑    花新城南苑      莲花新赘城南苑  舰花新南        花新成南
```

**第一个疑问**：我的结果不是 #号 连接，是空格
**第二个疑问**：执行对齐脚本，scripts/align_cal_werdur_fast.py 时，使用上面的数据结果不能执行，因为这个脚本需要2个参数，第一个参数 为 使用#号连接的4个候选文件，第二个参数是 候选集的目标文件。 上面的结果不符合这个脚本，不能正常的走下去
**第三个疑问**：我手动构造了 align_cal_werdur_fast.py 这个文件的2个参数文件，使其可以自行 ，但是执行的结果和你的也不一样，我的对每个候选只有一个0或-1或1，没有对每个字 进行标记。请看下我的结果文件（*src.werdur.full）示例：
`广州市房地产中介协会分析 1 ||| 广州市房地产中介协会分系 0 ||| 广州市房地产中介协会分许 0 ||| 广州市房地产中介协会分享 0 |||| 1 ||| -1 ||| -1 ||| -1`
但是你的结果是：
`|||| 0 -2 1 1 0 ||| -1 1 1 1 0 ||| 1 1 1 1 0`

我不知道我的操作为什么有这么多的不同，希望能得到一些帮助，万分感谢！！
