### ISSUE TITLE
FastCorrect: train_ft.sh脚本报错

### ISSUE THREAD

**Issue by whz-NJ** [microsoft/NeuralSpeech#52]
我使用自己的ASR数据集，并执行align_cal_werdur_v2.py进行对齐，得到test.zh_CN、test.zh_CN_tgt、valid.zh_CN、valid_zh_CN_tgt，再执行 data-gen.sh脚本进行二值化。最后执行train_ft.sh对提供的fastcorrect_pretrain.pt模型进行微调，但language_pair_dataset.py脚本在下面的红框位置报了错误，不明白哪里出错了，请帮忙看看，谢谢！
![image](https://user-images.githubusercontent.com/41171402/181716749-ce0dab41-0d71-4168-9b72-abf083a1f07d.png)
堆栈信息：
Traceback (most recent call last):
  File "/root/.local/conda/envs/fastcorrect/bin/fairseq-train", line 11, in <module>
    sys.exit(cli_main())
  File "/root/.local/conda/envs/fastcorrect/lib/python3.7/site-packages/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/root/.local/conda/envs/fastcorrect/lib/python3.7/site-packages/fairseq/distributed_utils.py", line 301, in call_main
    main(args, **kwargs)
  File "/root/.local/conda/envs/fastcorrect/lib/python3.7/site-packages/fairseq_cli/train.py", line 114, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "/root/.local/conda/envs/fastcorrect/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 208, in load_checkpoint
    epoch=itr_state["epoch"], load_dataset=True, **passthrough_args
  File "/root/.local/conda/envs/fastcorrect/lib/python3.7/site-packages/fairseq/trainer.py", line 382, in get_train_iterator
    self.reset_dummy_batch(batch_iterator.first_batch)
  File "/root/.local/conda/envs/fastcorrect/lib/python3.7/site-packages/fairseq/data/iterators.py", line 288, in first_batch
    return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])
  File "/root/.local/conda/envs/fastcorrect/lib/python3.7/site-packages/fairseq/data/iterators.py", line 288, in <listcomp>
    return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])
  File "/root/fastcorrect/FC_utils/language_pair_dataset.py", line 438, in __getitem__
    assert src_item_length % 2 == 1
AssertionError

**Comment by whz-NJ** [comment]
原因找到了，因为我构造的 train.zh_CN、train.zh_CN_tgt 文件中有空白行导致，删除后正常。
