### ISSUE TITLE
RuntimeError: The size of tensor a (0) must match the size of tensor b (2) at non-singleton dimension 1

### ISSUE THREAD

**Issue by qubo** [microsoft/NeuralSpeech#61]
hi 
thank you for sharing such a great work!

when i run the "run/test_ft.sh" as the last step in Readme.md, i got error as title, details error as follows:

Traceback (most recent call last):
  File "eval_aishell_nbest.py", line 94, in <module>
    batched_hypos, exc_time = transf_gec.generate(binarized, nbest_infer=nbest_num, nbest_infer_type=nbest_infer_type, iter_decode_max_iter=iter_decode_max_iter)
  File "/root/neuralspeech/FastCorrect2/FC_utils/hub_utils_fc.py", line 184, in generate
    generator, self.models, batch, nbest_infer_type=nbest_infer_type, **inference_step_args
  File "/root/neuralspeech/FastCorrect2/FastCorrect/fastcorrect_task.py", line 396, in inference_step
    models, sample, prefix_tokens=prefix_tokens, constraints=constraints, werdur_gt_str=werdur_gt_str, nbest_infer_type=nbest_infer_type)
  File "/usr/local/python3/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/root/neuralspeech/FastCorrect2/FC_utils/fastcorrect_generator.py", line 226, in generate
    prev_decoder_out, encoder_out, **decoder_options
  File "/root/neuralspeech/FastCorrect2/FastCorrect/fastcorrect_model.py", line 451, in forward_decoder
    to_be_edited=to_be_edited_pred, for_wer_gather=for_wer_gather
  File "/usr/local/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/fairseq/models/nat/fairseq_nat_model.py", line 41, in wrapper
    self, normalize=normalize, encoder_out=encoder_out, *args, **kwargs
  File "/root/neuralspeech/FastCorrect2/FastCorrect/fastcorrect_model.py", line 870, in forward
    to_be_edited=to_be_edited, for_wer_gather=for_wer_gather, debug_src_tokens=debug_src_tokens, debug_tgt_tokens=debug_tgt_tokens
  File "/root/neuralspeech/FastCorrect2/FastCorrect/fastcorrect_model.py", line 957, in extract_features
    src_embd, src_mask, prev_output_tokens.ne(self.padding_idx), wer_dur, to_be_edited, for_wer_gather, debug_src_tokens=debug_src_tokens, debug_tgt_tokens=debug_tgt_tokens
  File "/root/neuralspeech/FastCorrect2/FastCorrect/fastcorrect_model.py", line 1033, in forward_wer_dur_embedding
    to_reshape = to_reshape * tgt_masks[:, :, None]
RuntimeError: The size of tensor a (0) must match the size of tensor b (2) at non-singleton dimension 

i modified the run/test.ft.sh as follows:
-----------
#SAVE_DIR=    #<PATH-to-AISHELL1-Save-Dir>
SAVE_DIR="/root/output_dir/aishell1_save_dir"

test_epochs=55  # Should be decided by dev set performance
-----------

in SAVE_DIR, i have "checkpoint55.pt" as the  result file of run/train_ft.sh 

could you advise?

**Comment by qubo** [comment]
i paused just before the error occurs and check the tensors as follows:

> /root/neuralspeech/FastCorrect2/FastCorrect/fastcorrect_model.py(1033)forward_wer_dur_embedding()
-> to_reshape = to_reshape * tgt_masks[:, :, None]
(Pdb) to_reshape
tensor([], device='cuda:0', size=(1, 0, 512))
(Pdb) to_reshape.size()
torch.Size([1, 0, 512])
(Pdb) tgt_masks.size()
torch.Size([1, 2])
(Pdb) tgt_masks[:, :, None].size()
torch.Size([1, 2, 1])

both tensors are not empty, can you advise?

**Comment by guantao18** [comment]
> solve this

我也遇到过，我把fairseq0.12卸载了，换成论文中要求的fairseq=0.10.1，这个错误就没了
