### ISSUE TITLE
valueerror: expected sequence of length 3 at dim 1 (got 2)

### ISSUE THREAD

**Issue by piekey1994** [microsoft/NeuralSpeech#65]
我用自己的数据生成了一份训练集，也通过data-gen.sh生成了bin文件，然后开始训练的时候就报错了
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/data/k2/venv_k2/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/k2/venv_k2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/k2/venv_k2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/asr_correct/FastCorrect2/FC_utils/language_pair_dataset.py", line 835, in __getitem__
    raise err
  File "/data/asr_correct/FastCorrect2/FC_utils/language_pair_dataset.py", line 832, in __getitem__
    for_wer_gather = torch.LongTensor(for_wer_gather_list).transpose(0, 1)
ValueError: expected sequence of length 3 at dim 1 (got 2)

我看了一下源码，这里的for_wer_gather_list是[[0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 2], [0, 1, 2]]
不明白是什么原因

**Comment by piekey1994** [comment]
> I think the source file is not aligned with the target rightly. You can check 1) each source token has a duration in the alignment result; 2) the sum of the absolute value of all durations are the length of target sentence; 3) there is no empty source sentence nor target sentence.

Yes, I found some sentences with only one <void> character appearing in src. After removing these sentences, there is no error.
