### ISSUE TITLE
Checkpoint processing errors both in priorgrad and lightspeech

### ISSUE THREAD

**Issue by credo99** [microsoft/NeuralSpeech#97]
Again, as mentioned below, errors probably due to unproper matching between python code and reuired filenames for processing (similar to the Priorgrad bug related to checkpoints file processing):

In Lightspeech:

E:\neuralspeech\LightSpeech>python tasks/lightspeech_inference.py --config configs/tts/lj/lightspeech.yaml --exp_name lightspeech --reset --inference_text inference_text.txt
| set hparams:
accumulate_grad_batches: 1, activation: relu, arch: 2 7 4 3 5 6 3 4, attn_constraint: True, audio_num_mel_bins: 80,
audio_sample_rate: 22050, base_config: configs/tts/transformer_tts.yaml, check_val_every_n_epoch: 10, clip_grad_norm: 1, data_dir: data/ljspeech,
debug: False, dec_ffn_kernel_size: 9, dec_layers: 4, dict_file: dict, dropout: 0.2,
dur_predictor_kernel: 3, dur_predictor_layer: 2, enc_ffn_kernel_size: 9, enc_layers: 4, endless_ds: True,
ffn_kernel_size: 9, ffn_padding: SAME, filter_size: 1024, fmax: 7600, fmin: 80,
gen_dir_name: , gen_wav_denoise: False, griffin_lim_iters: 60, hidden_size: 256, hop_size: 256,
indexed_ds: True, infer: False, inference_text: inference_text.txt, lambda_dur: 1.0, lambda_energy: 1.0,
lambda_pitch: 1.0, lambda_uv: 1.0, latent_size: 32, log_interval: 100, loud_norm: False,
lr: 2.0, magnitude_power: 1, max_epochs: 1000, max_eval_sentences: 1, max_eval_tokens: 60000,
max_frames: 1550, max_input_tokens: 200, max_sentences: -1, max_tokens: 28000, max_updates: 100000,
mel_loss: l1, min_level_db: -100, n_fft: 1024, num_sanity_val_steps: 5, num_spk: 1,
optimizer_adam_beta1: 0.9, optimizer_adam_beta2: 0.98, out_wav_norm: False, pitch_loss: l1, pitch_predictor_layer: 5,
power: 1, predictor_hidden: 256, predictor_layer_type: sepconv, predictor_sg: True, prenet_hidden_size: 32,
pretrain_fs_ckpt: , profile_infer: False, raw_data_dir: data/raw/LJSpeech-1.1, ref_hidden_and_stride: ['128,2', '128,2', '128,1', '256,1', '256,1', '256,1'], ref_level_db: 20,
ref_norm_layer: bn_nonpad, resume_from_checkpoint: , save_ckpt: True, seed: 1234, sep_dur_loss: True,
show_progress_bar: True, sort_by_len: True, stop_token_weight: 5.0, test_num: 100, test_set_name: test,
train_set_name: train, use_amp: False, use_energy_embed: False, use_gt_dur: False, use_new_ffn: True,
use_pitch_embed: True, use_ref_enc: False, use_ref_tfm: False, use_spk_embed: False, use_spk_id: False,
use_training: False, use_uv: True, val_check_interval: 1000, valid_set_name: valid, validate: False,
vocoder: pwg, vocoder_ckpt: , warmup_updates: 2000, weight_decay: 0, win_size: 1024,
work_dir: checkpoints/lightspeech,
05/08 11:08:19 AM Model Size: 1771349
INFO: located checkpoint checkpoints/lightspeech\model_ckpt_steps_100000.ckpt. loading...
Traceback (most recent call last):
  File "tasks/lightspeech_inference.py", line 34, in <module>
    task.prepare_vocoder()
  File "E:\neuralspeech\LightSpeech\tasks\lightspeech.py", line 548, in prepare_vocoder
    ckpt = sorted(ckpts, key=
  File "E:\neuralspeech\LightSpeech\tasks\lightspeech.py", line 549, in <lambda>
    lambda x: int(re.findall(f'{base_dir}/checkpoint-(\d+)steps.pkl', x)[0]))[-1]
IndexError: list index out of range

BTW, why does the code look for a Pickle file when the provided checkpoints archive does not contain one?

**Comment by renqianluo** [comment]
The code provided is loading the vocoder model checkpoint, which should be downloaded and placed in the correct path as in the [README.md](https://github.com/microsoft/NeuralSpeech/tree/master/LightSpeech#5-download-pre-trained-vocoder).

**Comment by credo99** [comment]
> The code provided is loading the vocoder model checkpoint, which should be downloaded and placed in the correct path as in the [README.md](https://github.com/microsoft/NeuralSpeech/tree/master/LightSpeech#5-download-pre-trained-vocoder).

Please provide a google colab environment replicating the Lightspeech repo so I could test it there and then implement it step by step on windows! Thank you
